// Copyright 2020 DeepMind Technologies Limited
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#include "dm_robotics/mujoco/mjlib.h"

#include <string>

#include <mujoco/mujoco.h>  //NOLINT

namespace dm_robotics {

#define MJLIB_INIT(name) name(::name)

MjLib::MjLib(const std::string& libmujoco_path, int dlopen_flags)
    : MJLIB_INIT(mj_defaultVFS),
      MJLIB_INIT(mj_addFileVFS),
      MJLIB_INIT(mj_makeEmptyFileVFS),
      MJLIB_INIT(mj_findFileVFS),
      MJLIB_INIT(mj_deleteFileVFS),
      MJLIB_INIT(mj_deleteVFS),
      MJLIB_INIT(mj_saveLastXML),
      MJLIB_INIT(mj_freeLastXML),
      MJLIB_INIT(mj_printSchema),
      MJLIB_INIT(mj_step),
      MJLIB_INIT(mj_step1),
      MJLIB_INIT(mj_step2),
      MJLIB_INIT(mj_forward),
      MJLIB_INIT(mj_inverse),
      MJLIB_INIT(mj_forwardSkip),
      MJLIB_INIT(mj_inverseSkip),
      MJLIB_INIT(mj_defaultLROpt),
      MJLIB_INIT(mj_defaultSolRefImp),
      MJLIB_INIT(mj_defaultOption),
      MJLIB_INIT(mj_defaultVisual),
      MJLIB_INIT(mj_copyModel),
      MJLIB_INIT(mj_saveModel),
      MJLIB_INIT(mj_loadModel),
      MJLIB_INIT(mj_deleteModel),
      MJLIB_INIT(mj_sizeModel),
      MJLIB_INIT(mj_makeData),
      MJLIB_INIT(mj_copyData),
      MJLIB_INIT(mj_resetData),
      MJLIB_INIT(mj_resetDataDebug),
      MJLIB_INIT(mj_resetDataKeyframe),
      MJLIB_INIT(mj_deleteData),
      MJLIB_INIT(mj_resetCallbacks),
      MJLIB_INIT(mj_setConst),
      MJLIB_INIT(mj_setLengthRange),
      MJLIB_INIT(mj_printModel),
      MJLIB_INIT(mj_printData),
      MJLIB_INIT(mju_printMat),
      MJLIB_INIT(mju_printMatSparse),
      MJLIB_INIT(mj_fwdPosition),
      MJLIB_INIT(mj_fwdVelocity),
      MJLIB_INIT(mj_fwdActuation),
      MJLIB_INIT(mj_fwdAcceleration),
      MJLIB_INIT(mj_fwdConstraint),
      MJLIB_INIT(mj_Euler),
      MJLIB_INIT(mj_RungeKutta),
      MJLIB_INIT(mj_invPosition),
      MJLIB_INIT(mj_invVelocity),
      MJLIB_INIT(mj_invConstraint),
      MJLIB_INIT(mj_compareFwdInv),
      MJLIB_INIT(mj_sensorPos),
      MJLIB_INIT(mj_sensorVel),
      MJLIB_INIT(mj_sensorAcc),
      MJLIB_INIT(mj_energyPos),
      MJLIB_INIT(mj_energyVel),
      MJLIB_INIT(mj_checkPos),
      MJLIB_INIT(mj_checkVel),
      MJLIB_INIT(mj_checkAcc),
      MJLIB_INIT(mj_kinematics),
      MJLIB_INIT(mj_comPos),
      MJLIB_INIT(mj_camlight),
      MJLIB_INIT(mj_tendon),
      MJLIB_INIT(mj_transmission),
      MJLIB_INIT(mj_crb),
      MJLIB_INIT(mj_factorM),
      MJLIB_INIT(mj_solveM),
      MJLIB_INIT(mj_solveM2),
      MJLIB_INIT(mj_comVel),
      MJLIB_INIT(mj_passive),
      MJLIB_INIT(mj_subtreeVel),
      MJLIB_INIT(mj_rne),
      MJLIB_INIT(mj_rnePostConstraint),
      MJLIB_INIT(mj_collision),
      MJLIB_INIT(mj_makeConstraint),
      MJLIB_INIT(mj_projectConstraint),
      MJLIB_INIT(mj_referenceConstraint),
      MJLIB_INIT(mj_constraintUpdate),
      MJLIB_INIT(mj_addContact),
      MJLIB_INIT(mj_isPyramidal),
      MJLIB_INIT(mj_isSparse),
      MJLIB_INIT(mj_isDual),
      MJLIB_INIT(mj_mulJacVec),
      MJLIB_INIT(mj_mulJacTVec),
      MJLIB_INIT(mj_jac),
      MJLIB_INIT(mj_jacBody),
      MJLIB_INIT(mj_jacBodyCom),
      MJLIB_INIT(mj_jacGeom),
      MJLIB_INIT(mj_jacSite),
      MJLIB_INIT(mj_jacPointAxis),
      MJLIB_INIT(mj_name2id),
      MJLIB_INIT(mj_id2name),
      MJLIB_INIT(mj_fullM),
      MJLIB_INIT(mj_mulM),
      MJLIB_INIT(mj_mulM2),
      MJLIB_INIT(mj_addM),
      MJLIB_INIT(mj_applyFT),
      MJLIB_INIT(mj_objectVelocity),
      MJLIB_INIT(mj_objectAcceleration),
      MJLIB_INIT(mj_contactForce),
      MJLIB_INIT(mj_differentiatePos),
      MJLIB_INIT(mj_integratePos),
      MJLIB_INIT(mj_normalizeQuat),
      MJLIB_INIT(mj_local2Global),
      MJLIB_INIT(mj_getTotalmass),
      MJLIB_INIT(mj_setTotalmass),
      MJLIB_INIT(mj_version),
      MJLIB_INIT(mj_ray),
      MJLIB_INIT(mj_rayHfield),
      MJLIB_INIT(mj_rayMesh),
      MJLIB_INIT(mju_rayGeom),
      MJLIB_INIT(mju_raySkin),
      MJLIB_INIT(mjv_defaultCamera),
      MJLIB_INIT(mjv_defaultPerturb),
      MJLIB_INIT(mjv_room2model),
      MJLIB_INIT(mjv_model2room),
      MJLIB_INIT(mjv_cameraInModel),
      MJLIB_INIT(mjv_cameraInRoom),
      MJLIB_INIT(mjv_frustumHeight),
      MJLIB_INIT(mjv_alignToCamera),
      MJLIB_INIT(mjv_moveCamera),
      MJLIB_INIT(mjv_movePerturb),
      MJLIB_INIT(mjv_moveModel),
      MJLIB_INIT(mjv_initPerturb),
      MJLIB_INIT(mjv_applyPerturbPose),
      MJLIB_INIT(mjv_applyPerturbForce),
      MJLIB_INIT(mjv_averageCamera),
      MJLIB_INIT(mjv_select),
      MJLIB_INIT(mjv_defaultOption),
      MJLIB_INIT(mjv_defaultFigure),
      MJLIB_INIT(mjv_initGeom),
      MJLIB_INIT(mjv_makeConnector),
      MJLIB_INIT(mjv_defaultScene),
      MJLIB_INIT(mjv_makeScene),
      MJLIB_INIT(mjv_freeScene),
      MJLIB_INIT(mjv_updateScene),
      MJLIB_INIT(mjv_addGeoms),
      MJLIB_INIT(mjv_makeLights),
      MJLIB_INIT(mjv_updateCamera),
      MJLIB_INIT(mjv_updateSkin),
      MJLIB_INIT(mjr_defaultContext),
      MJLIB_INIT(mjr_makeContext),
      MJLIB_INIT(mjr_changeFont),
      MJLIB_INIT(mjr_addAux),
      MJLIB_INIT(mjr_freeContext),
      MJLIB_INIT(mjr_uploadTexture),
      MJLIB_INIT(mjr_uploadMesh),
      MJLIB_INIT(mjr_uploadHField),
      MJLIB_INIT(mjr_restoreBuffer),
      MJLIB_INIT(mjr_setBuffer),
      MJLIB_INIT(mjr_readPixels),
      MJLIB_INIT(mjr_drawPixels),
      MJLIB_INIT(mjr_blitBuffer),
      MJLIB_INIT(mjr_setAux),
      MJLIB_INIT(mjr_blitAux),
      MJLIB_INIT(mjr_text),
      MJLIB_INIT(mjr_overlay),
      MJLIB_INIT(mjr_maxViewport),
      MJLIB_INIT(mjr_rectangle),
      MJLIB_INIT(mjr_figure),
      MJLIB_INIT(mjr_render),
      MJLIB_INIT(mjr_finish),
      MJLIB_INIT(mjr_getError),
      MJLIB_INIT(mjr_findRect),
      MJLIB_INIT(mjui_themeSpacing),
      MJLIB_INIT(mjui_themeColor),
      MJLIB_INIT(mjui_add),
      MJLIB_INIT(mjui_resize),
      MJLIB_INIT(mjui_update),
      MJLIB_INIT(mjui_event),
      MJLIB_INIT(mjui_render),
      MJLIB_INIT(mju_error),
      MJLIB_INIT(mju_error_i),
      MJLIB_INIT(mju_error_s),
      MJLIB_INIT(mju_warning),
      MJLIB_INIT(mju_warning_i),
      MJLIB_INIT(mju_warning_s),
      MJLIB_INIT(mju_clearHandlers),
      MJLIB_INIT(mju_malloc),
      MJLIB_INIT(mju_free),
      MJLIB_INIT(mj_warning),
      MJLIB_INIT(mju_writeLog),
      MJLIB_INIT(mju_zero3),
      MJLIB_INIT(mju_copy3),
      MJLIB_INIT(mju_scl3),
      MJLIB_INIT(mju_add3),
      MJLIB_INIT(mju_sub3),
      MJLIB_INIT(mju_addTo3),
      MJLIB_INIT(mju_subFrom3),
      MJLIB_INIT(mju_addToScl3),
      MJLIB_INIT(mju_addScl3),
      MJLIB_INIT(mju_normalize3),
      MJLIB_INIT(mju_norm3),
      MJLIB_INIT(mju_dot3),
      MJLIB_INIT(mju_dist3),
      MJLIB_INIT(mju_rotVecMat),
      MJLIB_INIT(mju_rotVecMatT),
      MJLIB_INIT(mju_cross),
      MJLIB_INIT(mju_zero4),
      MJLIB_INIT(mju_unit4),
      MJLIB_INIT(mju_copy4),
      MJLIB_INIT(mju_normalize4),
      MJLIB_INIT(mju_zero),
      MJLIB_INIT(mju_copy),
      MJLIB_INIT(mju_sum),
      MJLIB_INIT(mju_L1),
      MJLIB_INIT(mju_scl),
      MJLIB_INIT(mju_add),
      MJLIB_INIT(mju_sub),
      MJLIB_INIT(mju_addTo),
      MJLIB_INIT(mju_subFrom),
      MJLIB_INIT(mju_addToScl),
      MJLIB_INIT(mju_addScl),
      MJLIB_INIT(mju_normalize),
      MJLIB_INIT(mju_norm),
      MJLIB_INIT(mju_dot),
      MJLIB_INIT(mju_mulMatVec),
      MJLIB_INIT(mju_mulMatTVec),
      MJLIB_INIT(mju_transpose),
      MJLIB_INIT(mju_mulMatMat),
      MJLIB_INIT(mju_mulMatMatT),
      MJLIB_INIT(mju_mulMatTMat),
      MJLIB_INIT(mju_sqrMatTD),
      MJLIB_INIT(mju_transformSpatial),
      MJLIB_INIT(mju_rotVecQuat),
      MJLIB_INIT(mju_negQuat),
      MJLIB_INIT(mju_mulQuat),
      MJLIB_INIT(mju_mulQuatAxis),
      MJLIB_INIT(mju_axisAngle2Quat),
      MJLIB_INIT(mju_quat2Vel),
      MJLIB_INIT(mju_subQuat),
      MJLIB_INIT(mju_quat2Mat),
      MJLIB_INIT(mju_mat2Quat),
      MJLIB_INIT(mju_derivQuat),
      MJLIB_INIT(mju_quatIntegrate),
      MJLIB_INIT(mju_quatZ2Vec),
      MJLIB_INIT(mju_mulPose),
      MJLIB_INIT(mju_negPose),
      MJLIB_INIT(mju_trnVecPose),
      MJLIB_INIT(mju_cholFactor),
      MJLIB_INIT(mju_cholSolve),
      MJLIB_INIT(mju_cholUpdate),
      MJLIB_INIT(mju_eig3),
      MJLIB_INIT(mju_muscleGain),
      MJLIB_INIT(mju_muscleBias),
      MJLIB_INIT(mju_muscleDynamics),
      MJLIB_INIT(mju_encodePyramid),
      MJLIB_INIT(mju_decodePyramid),
      MJLIB_INIT(mju_springDamper),
      MJLIB_INIT(mju_min),
      MJLIB_INIT(mju_max),
      MJLIB_INIT(mju_sign),
      MJLIB_INIT(mju_round),
      MJLIB_INIT(mju_type2Str),
      MJLIB_INIT(mju_str2Type),
      MJLIB_INIT(mju_warningText),
      MJLIB_INIT(mju_isBad),
      MJLIB_INIT(mju_isZero),
      MJLIB_INIT(mju_standardNormal),
      MJLIB_INIT(mju_f2n),
      MJLIB_INIT(mju_n2f),
      MJLIB_INIT(mju_d2n),
      MJLIB_INIT(mju_n2d),
      MJLIB_INIT(mju_insertionSort),
      MJLIB_INIT(mju_Halton),
      MJLIB_INIT(mju_strncpy),
      MJLIB_INIT(mjcb_passive),
      MJLIB_INIT(mjcb_control),
      MJLIB_INIT(mjcb_contactfilter),
      MJLIB_INIT(mjcb_sensor),
      MJLIB_INIT(mjcb_time),
      MJLIB_INIT(mjcb_act_dyn),
      MJLIB_INIT(mjcb_act_gain),
      MJLIB_INIT(mjcb_act_bias),
      MJLIB_INIT(mjCOLLISIONFUNC),
      MJLIB_INIT(mj_loadXML) {}

MjLib::~MjLib() = default;

#undef MJLIB_INIT

}  // namespace dm_robotics
